# Generated by Django 3.2 on 2021-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Action',
            field=models.CharField(default='update', max_length=10),
        ),
    ]
